### ISSUE TITLE
Find new .tpl files and add to config.php / database

### ISSUE THREAD

**Issue by Deesen** [dzhuryn/StaticElements-for-MODX-Evo#6]
If I install StaticElements on new website, and I want to add my standard eform-chunks it would be great to just add some standard files

```
elements/chunks/eform_contactform.tpl
elements/chunks/eform_contactform_tpl.tpl
elements/chunks/eform_contactform_report_tpl.tpl
```

and these 3 new elements get added to the database / config.php . Maybe a button like "Find/add new files"

**Comment by dzhuryn** [comment]
you can copy you chunks into folder elements/chunks. Refresh anyone page on you website.and then you can see this chunsk in database.
If you have question for me add my skype. volodyadjuryn1

**Comment by dzhuryn** [comment]
For create element you can 
1. Use modx manager
2. Or create file in folder

**Comment by Deesen** [comment]
Had no time yesterday to test. Today I opened again my localhost and the new chunk appeared :-). This is absolutely FANTASTIC job man, thank you very much!

But do you think "OnWebPageInit" is perfect? Maybe its more secure etc to inject a "Sync"-button via jquery above manager´s tab-buttons (or as new tab, or a button per category Chunks/Snippets etc). Pointing to index.php?a=76**&syncStaticEl=1&seCategory=chunks** . So chunks can be changed only when logged into manager, not already by changing .tpl files (through hacks?).

I think a plugin-option "Sync on WebPageInit" enabled/disabled would be perfect, together with the Sync-button.

**Comment by dzhuryn** [comment]
i think i add parameter workWhenAdminLogged.
When this parameter have value "1", then plugin work only when admin logged.
When this parameter have value "1", thenplugin work every time.

**Comment by Deesen** [comment]
Also great, thanks!
